server:
  port: 8081

### ?? ??? ???? applcation ??? ???? Form Login? ?? oauth2 ??? ?? ??? ?????
spring:
  security:
    oauth2:
      client:
        ######### ????? ?? #########
        registration:
          # unique key
          keycloak:
            # Oauth 2.0 ?? ?? ??
            authorization-grant-type: authorization_code
            # ????? ?? ????? ???
            client-id: oauth2-client-app
            # ????? ?? (???? ??? ???)
            client-name: oauth2-client-app
            # ????? ???
            client-secret: 6DXU8UzsWxOypCOqbeVjLq0sUaQMculC
            # ?????? ?? ?? ?? ? ?????? ????? ?? ?? (????? ?? ?? ??? ???)
            redirect-uri: http://localhost:8081/login/oauth2/code/ceycloak
            # ????? ???? ?? ?? (client_secret_basic, client_secret_post)
            client-authentication-method: client_secret_basic
            # ??? ?? ?? ??
            scope: openid,email
        ######### ?? ?? ?? #########
        provider:
          # unique key
          keycloak:
              # Oauth 2.0 ?? ?? ?? ?? ???
              authorization-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/auth
              # ??? ??? ?? (Base Uri)
              issuer-uri: http://localhost:8080/realms/oauth2
              # Oauth 2.0 JwtSetUri ?? ???
              jwk-set-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/certs
              # Oauth 2.0 ?? ?? ???
              token-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/token
              # Oauth 2.0 userInfo ?? ???
              user-info-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/userinfo
              # Oauth 2.0 ????? ???? Key
              user-name-attribute: preferred_username