server:
  port: 8081

### 해당 설정을 등록하면 application 접근시 시큐리티 Form Login이 아닌 oauth2 서버를 통한 인증을 처리합니다
spring:
  security:
    oauth2:
      client:
        ######### 클라이언트 설정 #########
        registration:
          keycloak:
            authorization-grant-type: authorization_code
            client-id: oauth2-client-app
            client-name: oauth2-client-app
            client-secret: 5qKZGq4azbkkSis19AvI2hU1lw9V3eQ7
            redirect-uri: http://localhost:8081/login/oauth2/code/keycloak
            client-authentication-method: client_secret_basic
            scope: profile,email,openid
            provider: keycloak
          google:
            client-id: 303918678932-4b0hug1rf226dpj022jkl083nkv7q0d5.apps.googleusercontent.com
            client-secret: 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
            scope: profile,email,openid
          naver:
            client-id: UwwvxdTjzLLCa1Zc4nYV
            client-secret: YCkpwJuRd5
            scope: profile,email # 네이버는 openid 를 지원하지 않는
            authorization-grant-type: authorization_code
            client-name: naver-client-app
            redirect-uri: http://localhost:8081/login/oauth2/code/naver
          kakao:
            client-id: 6aca63e773a28e941f590d65893fa900 # REST API Key
            client-secret: QRGYmnewrcK8WAA3eeCQ4qSOFpP2Kyvt
            scope: profile_nickname, profile_image, account_email
            authorization-grant-type: authorization_code
            client-name: client-app
            redirect-uri: http://localhost:8081/login/oauth2/code/kakao

        ######### 인가 서버 설정 #########
        provider:
          keycloak:
            authorization-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/auth
            issuer-uri: http://localhost:8080/realms/oauth2
            jwk-set-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/certs
            token-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/token
            user-info-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            issuer-uri: https://kauth.kakao.com
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            jwk-set-uri: https://kauth.kakao.com/./well-known/jwks.json
            user-name-attribute: id